export const putObject = jest.fn(async () => ({}))
export const getObject = jest.fn(async () => ({ Body: Buffer.from('') }))
export const deleteObject = jest.fn(async () => ({}))
export const copyObject = jest.fn(async () => ({}))
export const copyObjects = jest.fn(async () => ({}))
export const listBucketObjects = jest.fn(async () => ({ Contents: [] }))
export const listDirObjects = jest.fn(async () => ({ Contents: [], CommonPrefixes: [] }))
export const createBucket = jest.fn(async () => ({}))
export const createS3Folder = jest.fn(async () => ({}))
export const removeS3Folder = jest.fn(async () => ({}))
